import type { NextFontWithVariable } from 'next/dist/compiled/@next/font';

import { Geist, Geist_Mono } from 'next/font/google';
import './main.css';
import { AppChakraProvider } from '@/app/components/ui/AppChakraProvider';
import { Toaster } from '@/app/components/ui/Toaster';

const geistSans: NextFontWithVariable = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono: NextFontWithVariable = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = (props: { children: React.ReactNode }) => {
  const { children } = props;
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppChakraProvider>
          {children}
          <Toaster />
        </AppChakraProvider>
      </body>
    </html>
  );
};

export default RootLayout;
