import { Geist, Geist_Mono } from 'next/font/google'
import './main.css'
import type { NextFontWithVariable } from 'next/dist/compiled/@next/font'
import type { JSX } from 'react'
import { Provider } from '@/app/components/ui/Provider'
import { Toaster } from '@/app/components/ui/Toaster'

const geistSans: NextFontWithVariable = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono: NextFontWithVariable = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: { children: React.ReactNode }): JSX.Element {
  const { children } = props
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider>
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  )
}
